### ISSUE TITLE
Warning message: In xbrl_get_data(elements, xbrl_vars) : Rows with duplicated endDate

### ISSUE THREAD

**Issue by Stevo15025** [bergant/finstr#2]
Can you explain the following error? I'm unable to 

xbrl.vars <- xbrlDoAll(inst,prefix.out="test")
xbrl_urltest <- "http://www.sec.gov/Archives/edgar/data/73290/000151316216000678/bmra-20151130.xml"

 old_o <- options(stringsAsFactors = FALSE)

 xbrl_test <- xbrlDoAll(xbrl_urltest)

 sttest <- xbrl_get_statements(xbrl_test)
Warning message:
In xbrl_get_data(elements, xbrl_vars) : Rows with duplicated endDate

Financial statements repository
                                                         From         To         Rows  Columns
ConsolidatedIncomeStatement 2015-11-30 2015-11-30    2        19
ConsolidatedBalanceSheet       2015-05-31 2015-11-30    2        26
ConsolidatedCashFlow                <NA>           <NA>           0        26

Warning messages:
1: In min(x$endDate) : no non-missing arguments, returning NA
2: In max(x$endDate) : no non-missing arguments, returning NA

Why does consolidated cash flow have 0 rows?

**Comment by davidmerz** [comment]
The issue I have found is that some ElementIds do not have an endDate. From a financial reporting perspective, the company ends their accounting year i.e on Dec31, but does not publically report for a couple more months. An elementID that is reported on the day they release their earnings is another commonSharesOutstanding & companyEntityFloat...these elementIds do not have a normal cycle of startDate and endDate (amongst others) and cause that error.

I appreciate any other insight running <XBRL> & <finstr>.

**Comment by bergant** [comment]
In xbrl instance there can be many statements with different dimensions. __finstr__ simplified this by excluding statements with missing elements. In this case some elements were missing (GainLossOnSaleOfPropertyPlantEquipment in 2015 and IncreaseDecreaseInDeferredIncomeTaxes in 2014).

I updated (SHA: fda96796f688597d1175f1fc743376f3ffc0af18) `finstr::xbrl_get_statement` function by additional arguments:

- complete_only (if true, only complete statements are reported - same functionality as before)
- complete_first (if true, statements with missing first element is not included - recomended here)

Note: both arguments are `TRUE` by default. You have to set `complete_only` to `FALSE` to use `complete_first`.

Example:
    
    library(XBRL)
    xbrl_urltest <- "http://www.sec.gov/Archives/edgar/data/73290/000151316216000678/bmra-20151130.xml"
    old_o <- options(stringsAsFactors = FALSE)
    xbrl_test <- xbrlDoAll(xbrl_urltest)
    options(old_o)

    library(finstr)
    sttest <- xbrl_get_statements(xbrl_test, complete_only = FALSE)

Duplicated period warning is also removed. If more than one end date is present the statement will be displayed context id labels instead of end date. There are no changes in object structure (end date is still a column of statement data frame).
